### ISSUE TITLE
Billing Library 6.0.x is out now

### ISSUE THREAD

**Issue by kanetik** [michal-luszczuk/MakeBillingEasy#6]
[Mostly with support for alternative billing platforms, I guess](https://developer.android.com/google/play/billing/release-notes#5-2)

**Comment by kanetik** [comment]
Strike that - v6.0.0 is now out, with [better logging and tweaks to errors around connectivity](https://developer.android.com/google/play/billing/release-notes#6-0).

**Comment by kanetik** [comment]
Stike that as well. v7.0.0 is out now. I've [submitted a PR](https://github.com/michal-luszczuk/MakeBillingEasy/pull/8) to bring MBE up to speed with that.

**Comment by michal-luszczuk** [comment]
Thank you for this issue. Code is updated and will be released soon.

https://github.com/michal-luszczuk/MakeBillingEasy/issues/9
